image: registry.cn-hangzhou.aliyuncs.com/yx-repo/yunxicibase:0.3.0-debian


stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  script:
    - npm config set registry http://nexus.paas-pro.haier.net/repository/dts-npm-group/
    - npm i
    - npm run lint
    - npm test
    - npm run es5